---
image_resource:
  type: docker-image
  source:
    repository: malston/gradle-java-8
platform: linux
inputs:
  - name: repo
  - name: gradle
run:
  path: /bin/bash
  args: ["-c", "repo/ci/tasks/scripts/cats.sh smoke"]
params:
  CF_API:
  CF_USER:
  CF_PASSWORD:
  CF_ORG:
  CF_SPACE:
  CF_DOMAIN:
  CF_HOST_NAME:
